anchor_version = "0.19.0"

[workspace]
members = ["programs/step-staking"]

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://psytrbhymqlkfrhudd.dev.genesysgo.net:8899/"
wallet = "~/.config/solana/devnet.json"

# [provider]
# cluster = "localnet"
# wallet = "~/.config/solana/devnet.json"

[scripts]
test = "mocha -t 1000000 tests/"

[programs.localnet]
step_staking = "TesT35sGptoswsVkcLpUUe6U2iTJZE59on1Jno8Vdpg"

[programs.devnet]
step_staking = "StKLLTf7CQ9n5BgXPSDXENovLTCuNc7N2ehvTb6JZ5x"

[programs.testnet]
step_staking = "StKLLTf7CQ9n5BgXPSDXENovLTCuNc7N2ehvTb6JZ5x"

[programs.mainnet]
step_staking = "StKLLTf7CQ9n5BgXPSDXENovLTCuNc7N2ehvTb6JZ5x"